name: cli_cmds
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cli_script: ^0.2.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
